image: docker:20.10-dind

variables:
  DOCKER_BUILDKIT: 1
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: ${DOCKER_REGISTRY}

stages:
  - build
  - manifest

build_arm64v8:
  stage: build
  tags:
    - arm64v8
  variables:
    ARCH: arm64v8
  before_script:
    - docker info
  script:
    - docker build . -f Dockerfile -t ${DOCKER_REGISTRY}/neotrial/docker-events-exporter/docker-events-exporter:${CI_COMMIT_REF_SLUG}-${ARCH} --build-arg ARCH=${ARCH}
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push ${DOCKER_REGISTRY}/neotrial/docker-events-exporter/docker-events-exporter:${CI_COMMIT_REF_SLUG}-${ARCH}

build_amd64:
  stage: build
  tags:
    - amd64
  variables:
    ARCH: amd64
  before_script:
    - docker info
  script:
    - docker build . -f Dockerfile -t ${DOCKER_REGISTRY}/neotrial/docker-events-exporter/docker-events-exporter:${CI_COMMIT_REF_SLUG}-${ARCH} --build-arg ARCH=${ARCH}
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push ${DOCKER_REGISTRY}/neotrial/docker-events-exporter/docker-events-exporter:${CI_COMMIT_REF_SLUG}-${ARCH}

manifest:
  stage: manifest
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker manifest create ${DOCKER_REGISTRY}/neotrial/docker-events-exporter/docker-events-exporter:${CI_COMMIT_REF_SLUG} --amend ${DOCKER_REGISTRY}/neotrial/docker-events-exporter/docker-events-exporter:${CI_COMMIT_REF_SLUG}-amd64 --amend ${DOCKER_REGISTRY}/neotrial/docker-events-exporter/docker-events-exporter:${CI_COMMIT_REF_SLUG}-arm64v8
    - docker manifest push ${DOCKER_REGISTRY}/neotrial/docker-events-exporter/docker-events-exporter:${CI_COMMIT_REF_SLUG}
